// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250528063738_CreateInsuranceReportTable")]
    partial class CreateInsuranceReportTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.InsuranceReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CalimsProcessed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClaimsNotProcessed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClaimsNotReported")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InitialEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PolicyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReportId");

                    b.ToTable("InsuranceReports");
                });
#pragma warning restore 612, 618
        }
    }
}
